# Generated by Django 4.1.3 on 2022-11-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
