# Generated by Django 4.1.3 on 2022-11-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_member_attempts_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='attempts_number_game',
            field=models.IntegerField(default=3),
        ),
    ]
