# Generated by Django 4.1.3 on 2022-11-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_chat_attempts_number_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='number_number_game',
            field=models.IntegerField(default=0),
        ),
    ]
