# Generated by Django 4.1.3 on 2022-11-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_chat_number_number_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='trivia_mode',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='trivia_questions',
            field=models.IntegerField(default=1),
        ),
    ]
