# Generated by Django 4.1.3 on 2022-11-08 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_chat_trivia_mode_chat_trivia_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='trivia_questions',
            new_name='trivia_number_of_questions',
        ),
    ]
