# Generated by Django 4.1.3 on 2022-11-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_rename_trivia_questions_chat_trivia_number_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='trivia_questions',
            field=models.JSONField(default=''),
        ),
    ]
