# Generated by Django 4.1.3 on 2022-11-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_chat_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='actual_question',
            field=models.IntegerField(default=0),
        ),
    ]
