# Generated by Django 4.1.3 on 2022-11-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_chat_actual_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='answered_trivia',
            field=models.BooleanField(default=False),
        ),
    ]
