# Generated by Django 4.1.3 on 2022-11-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_chat_tivia_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='number_games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='trivia_games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='trivia_points',
            field=models.IntegerField(default=0),
        ),
    ]
