# Generated by Django 4.1.3 on 2022-11-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_member_number_games_won_member_trivia_games_won_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='trivia_actual_alternatives',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chat',
            name='trivia_last_alternatives',
            field=models.TextField(default=''),
        ),
    ]
