# Generated by Django 4.1.3 on 2022-11-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_chat_trivia_actual_alternatives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='attempts_code_game',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
