# Generated by Django 4.1.3 on 2022-11-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_chat_attempts_code_game_chat_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='code_points',
            field=models.IntegerField(default=0),
        ),
    ]
