# Generated by Django 4.1.3 on 2022-11-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_member_code_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='limit_number_game',
            field=models.IntegerField(default=0),
        ),
    ]
