# Generated by Django 4.1.3 on 2022-11-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_chat_limit_number_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='code_points',
            new_name='code_games_won',
        ),
    ]
